### ISSUE TITLE
Issue using generate_homologs()

### ISSUE THREAD

**Issue by claratejido** [saezlab/liana#137]
Hi Daniel!

I encountered the following error when using the test data example with show_homologene() and ortholog_resource:

> ```r
> > ortholog_resource <- generate_homologs(op_resource = op_resource,
> +                                        target_organism = 10090) # mouse
> [2024-02-03 20:34:11] [WARN]    [OmnipathR] Failed to download `https://ftp.ncbi.nih.gov/pub/HomoloGene/current/homologene.data` (attempt 1/3); error: HTTP error 404.
> [2024-02-03 20:34:17] [WARN]    [OmnipathR] Failed to download `https://ftp.ncbi.nih.gov/pub/HomoloGene/current/homologene.data` (attempt 2/3); error: HTTP error 404.
> [2024-02-03 20:34:22] [ERROR]   [OmnipathR] Failed to download `https://ftp.ncbi.nih.gov/pub/HomoloGene/current/homologene.data` (attempt 3/3); error: HTTP error 404.
> Error in open.connection(5L, "rb") : HTTP error 404.
> ```

I have the latest version of liana and OmnipathR, downloaded using: remotes::[install_github](https://remotes.r-lib.org/reference/install_github.html)("saezlab/OmnipathR"). For more information, find my session info below.

Thanks a lot in advance for your help,

Best wishes,

Clara

> sessionInfo()
R version 4.2.0 (2022-04-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblas-r0.3.3.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] magrittr_2.0.3      OmnipathR_3.11.1    lubridate_1.9.3     forcats_1.0.0       stringr_1.5.1      
 [6] purrr_1.0.2         readr_2.1.5         tidyr_1.3.1         tibble_3.2.1        tidyverse_2.0.0    
[11] liana_0.1.13        CellChat_1.6.1      igraph_1.6.0        SCpubr_2.0.2.9000   qs_0.25.7          
[16] metap_1.9           multtest_2.52.0     Biobase_2.58.0      BiocGenerics_0.44.0 openxlsx_4.2.5.2   
[21] dplyr_1.1.4         ggplot2_3.4.4       Seurat_5.0.1        SeuratObject_5.0.1  sp_2.1-3           

loaded via a namespace (and not attached):
  [1] rsvd_1.0.5                    statnet.common_4.9.0          ica_1.0-3                    
  [4] svglite_2.1.3                 foreach_1.5.2                 lmtest_0.9-40                
  [7] crayon_1.5.2                  rbibutils_2.2.16              MASS_7.3-57                  
 [10] nlme_3.1-157                  backports_1.4.1               basilisk_1.15.2004           
 [13] rlang_1.1.3                   XVector_0.38.0                ROCR_1.0-11                  
 [16] readxl_1.4.3                  irlba_2.3.5.1                 limma_3.54.2                 
 [19] filelock_1.0.3                stringfish_0.16.0             BiocParallel_1.32.6          
 [22] rjson_0.2.21                  bit64_4.0.5                   glue_1.7.0                   
 [25] pheatmap_1.0.12               rngtools_1.5.2                sctransform_0.4.1            
 [28] parallel_4.2.0                spatstat.sparse_3.0-3         AnnotationDbi_1.60.2         
 [31] dotCall64_1.1-1               spatstat.geom_3.2-8           tidyselect_1.2.0             
 [34] SummarizedExperiment_1.28.0   fitdistrplus_1.1-11           zoo_1.8-12                   
 [37] qqconf_1.3.2                  ggpubr_0.6.0                  ontologyIndex_2.11           
 [40] xtable_1.8-4                  ggnetwork_0.5.12              RcppHNSW_0.5.0               
 [43] evaluate_0.23                 scuttle_1.8.4                 Rdpack_2.6                   
 [46] cli_3.6.2                     zlibbioc_1.44.0               sn_2.1.1                     
 [49] rstudioapi_0.15.0             miniUI_0.1.1.1                logger_0.2.2                 
 [52] mathjaxr_1.6-0                fastDummies_1.7.3             shiny_1.8.0                  
 [55] BiocSingular_1.14.0           xfun_0.41                     clue_0.3-65                  
 [58] cluster_2.1.3                 KEGGREST_1.38.0               interactiveDisplayBase_1.34.0
 [61] ggrepel_0.9.5                 listenv_0.9.1                 Biostrings_2.66.0            
 [64] png_0.1-8                     future_1.33.1                 withr_3.0.0                  
 [67] bitops_1.0-7                  plyr_1.8.9                    cellranger_1.1.0             
 [70] dqrng_0.3.2                   coda_0.19-4.1                 pillar_1.9.0                 
 [73] RcppParallel_5.1.7            GlobalOptions_0.1.2           cachem_1.0.8                 
 [76] multcomp_1.4-25               GetoptLong_1.0.5              DelayedMatrixStats_1.20.0    
 [79] vctrs_0.6.5                   ellipsis_0.3.2                generics_0.1.3               
 [82] RApiSerialize_0.1.2           NMF_0.26                      tools_4.2.0                  
 [85] munsell_0.5.0                 DelayedArray_0.24.0           fastmap_1.1.1                
 [88] compiler_4.2.0                paintmap_1.0                  abind_1.4-5                  
 [91] httpuv_1.6.14                 plotly_4.10.4                 GenomeInfoDbData_1.2.9       
 [94] gridExtra_2.3                 edgeR_3.40.2                  lattice_0.20-45              
 [97] dir.expiry_1.6.0              deldir_2.0-2                  mutoss_0.1-13                
[100] utf8_1.2.4                    later_1.3.2                   BiocFileCache_2.4.0          
[103] jsonlite_1.8.8                ontoProc_1.18.0               scales_1.3.0                 
[106] ScaledMatrix_1.6.0            graph_1.74.0                  sparseMatrixStats_1.10.0     
[109] pbapply_1.7-2                 carData_3.0-5                 lazyeval_0.2.2               
[112] promises_1.2.1                car_3.1-2                     doParallel_1.0.17            
[115] goftest_1.2-3                 spatstat.utils_3.0-4          reticulate_1.35.0            
[118] sna_2.7-2                     checkmate_2.3.1               rmarkdown_2.25               
[121] sandwich_3.1-0                cowplot_1.1.3                 statmod_1.5.0                
[124] Rtsne_0.17                    selectr_0.4-2                 uwot_0.1.16                  
[127] survival_3.3-1                numDeriv_2016.8-1.1           yaml_2.3.8                   
[130] plotrix_3.8-4                 systemfonts_1.0.5             htmltools_0.5.7              
[133] memoise_2.0.1                 locfit_1.5-9.8                IRanges_2.32.0               
[136] viridisLite_0.4.2             digest_0.6.34                 mime_0.12                    
[139] rappdirs_0.3.3                registry_0.5-1                spam_2.10-0                  
[142] RSQLite_2.3.5                 future.apply_1.11.1           data.table_1.15.0            
[145] blob_1.2.4                    S4Vectors_0.36.2              splines_4.2.0                
[148] AnnotationHub_3.4.0           RCurl_1.98-1.14               broom_1.0.5                  
[151] hms_1.1.3                     colorspace_2.1-0              BiocManager_1.30.22          
[154] mnormt_2.1.1                  GenomicRanges_1.50.2          shape_1.4.6                  
[157] Rcpp_1.0.12                   RANN_2.6.1                    mvtnorm_1.2-4                
[160] circlize_0.4.15               fansi_1.0.6                   tzdb_0.4.0                   
[163] parallelly_1.36.0             R6_2.5.1                      grid_4.2.0                   
[166] ggridges_0.5.6                lifecycle_1.0.4               bluster_1.8.0                
[169] zip_2.3.1                     TFisher_0.2.0                 curl_5.2.0                   
[172] ggsignif_0.6.4                leiden_0.4.3.1                Matrix_1.6-5                 
[175] RcppAnnoy_0.0.22              TH.data_1.1-2                 RColorBrewer_1.1-3           
[178] iterators_1.0.14              spatstat.explore_3.2-6        htmlwidgets_1.6.4            
[181] beachmat_2.14.2               polyclip_1.10-6               network_1.18.2               
[184] timechange_0.3.0              rvest_1.0.3                   ComplexHeatmap_2.14.0        
[187] globals_0.16.2                patchwork_1.2.0               spatstat.random_3.2-2        
[190] progressr_0.14.0              codetools_0.2-18              matrixStats_1.2.0            
[193] metapod_1.6.0                 FNN_1.1.4                     prettyunits_1.2.0            
[196] SingleCellExperiment_1.20.1   dbplyr_2.4.0                  basilisk.utils_1.15.1        
[199] gridBase_0.4-7                RSpectra_0.16-1               GenomeInfoDb_1.34.9          
[202] gtable_0.3.4                  DBI_1.2.1                     ggalluvial_0.12.5            
[205] stats4_4.2.0                  tensor_1.5                    httr_1.4.7                   
[208] KernSmooth_2.23-20            vroom_1.6.5                   stringi_1.8.3                
[211] progress_1.2.3                reshape2_1.4.4                ontologyPlot_1.6             
[214] Rgraphviz_2.40.0              DT_0.31                       xml2_1.3.6                   
[217] BiocNeighbors_1.16.0          kableExtra_1.4.0              scattermore_1.2              
[220] BiocVersion_3.15.2            scran_1.26.2                  bit_4.0.5                    
[223] MatrixGenerics_1.10.0         spatstat.data_3.0-4           pkgconfig_2.0.3              
[226] rstatix_0.7.2                 knitr_1.45    

```

**Comment by dbdimitrov** [comment]
Hi @claratejido,

If you're still experiencing the issue - maybe @deeenes could help.

**Comment by deeenes** [comment]
Hi @claratejido,

Is your `OmnipathR` the latest from GitHub? Today it should use OMA as the default orthology resource, and I think we've fixed already the HomoloGene URL too. You can install the latest version this way:

```
library(remotes)
remotes::install_github('saezlab/OmnipathR')
```

Best,

Denes

**Comment by deeenes** [comment]
I was wrong in a couple of points here:

1) Indeed there was an issue with HomoloGene, it went offline, I think after 8 years of zombie existence NCBI finally killed it. Then last week I moved it [to our own server](https://rescued.omnipathdb.org/), into the so called "rescued" repo, so our software keep working seamlessly.

2) LIANA didn't use OMA, bc it relied directly on the HomoloGene access in OmnipathR. Now I filed a [PR](https://github.com/saezlab/liana/pull/141) to move LIANA from HomoloGene to OMA.

With this, I think orthology translation should be good, even better than it was before.

**Comment by Charmy0619** [comment]
Hi @deeenes,  
I still have an issue getting the orthology symbols for conversion, but it's a different error. Are you able to help? Thanks.
`
> show_homologene()
[2024-06-06 16:41:05] [SUCCESS] [OmnipathR] NCBI HomoloGene (rescued.omnipathdb.org): loaded 275237 records from cache
[2024-06-06 16:41:06] [WARN]    [OmnipathR] HTTP 403
[2024-06-06 16:41:06] [WARN]    [OmnipathR] Failed to download `https://www.ensembl.org/info/about/species.html` (attempt 1/3); error: HTTP 403
[2024-06-06 16:41:11] [WARN]    [OmnipathR] HTTP 403
[2024-06-06 16:41:11] [WARN]    [OmnipathR] Failed to download `https://www.ensembl.org/info/about/species.html` (attempt 2/3); error: HTTP 403
[2024-06-06 16:41:17] [WARN]    [OmnipathR] HTTP 403
[2024-06-06 16:41:17] [ERROR]   [OmnipathR] Failed to download `https://www.ensembl.org/info/about/species.html` (attempt 3/3); error: HTTP 403
Error in `map_chr()`:
i In index: 1.
Caused by error:
! HTTP 403
Run `rlang::last_trace()` to see where the error occurred.
> op_resource <- select_resource("Consensus")[[1]]
> ortholog_resource <- generate_homologs(op_resource = op_resource, target_organism = 10090) # mouse
[2024-06-06 16:41:33] [WARN]    [OmnipathR] HTTP 403
[2024-06-06 16:41:33] [WARN]    [OmnipathR] Failed to download `https://www.ensembl.org/info/about/species.html` (attempt 1/3); error: HTTP 403
[2024-06-06 16:41:38] [WARN]    [OmnipathR] HTTP 403
[2024-06-06 16:41:38] [WARN]    [OmnipathR] Failed to download `https://www.ensembl.org/info/about/species.html` (attempt 2/3); error: HTTP 403
[2024-06-06 16:41:44] [WARN]    [OmnipathR] HTTP 403
[2024-06-06 16:41:44] [ERROR]   [OmnipathR] Failed to download `https://www.ensembl.org/info/about/species.html` (attempt 3/3); error: HTTP 403
Error in `map_int()`:
i In index: 1.
Caused by error:
! HTTP 403
Run `rlang::last_trace()` to see where the error occurred.
> sessionInfo()
R version 4.3.2 (2023-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

time zone: America/Chicago
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] Seurat_5.0.1       magrittr_2.0.3     liana_0.1.13       OmnipathR_3.13.4   lubridate_1.9.3    forcats_1.0.0      stringr_1.5.1     
 [8] dplyr_1.1.4        purrr_1.0.2        readr_2.1.5        tidyr_1.3.1        tibble_3.2.1       ggplot2_3.4.4      tidyverse_2.0.0   
[15] SeuratObject_5.0.1 sp_2.1-2  `

**Comment by Dalhte** [comment]
Hello there !
I also have an issue with generate_homologs (and show_homologene())
I get : 
> show_homologene()
[2024-10-18 13:44:27] [SUCCESS] [OmnipathR] NCBI HomoloGene (rescued.omnipathdb.org): downloaded 2 records
Erreur dans UseMethod("pull") : 
  pas de méthode pour 'pull' applicable pour un objet de classe "list"

and 

> ortholog_resource <- generate_homologs(op_resource = op_resource,
+                                        target_organism = 10116) # Rat
[2024-10-18 13:45:26] [SUCCESS] [OmnipathR] NCBI HomoloGene (rescued.omnipathdb.org): downloaded 2 records
Erreur dans UseMethod("filter") : 
  pas de méthode pour 'filter' applicable pour un objet de classe "list"

Any idea ?
Best
David
